import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900", // Specify weight range if needed
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900", // Specify weight range if needed
});

// Metadata without viewport
export const metadata: Metadata = {
  title: "Create Next App", // Consider making this dynamic or more specific
  description: "Generated by create next app",
  authors: [{ name: "Your Name", url: "https://yourwebsite.com" }], // Example: Add author info
  keywords: ["Next.js", "React", "Web Development", "App"], // Add relevant keywords
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://yourwebsite.com", // Ensure this is set to your actual site URL
    images: "/path/to/og-image.jpg", // Optional: add Open Graph image
  },
};

// Export viewport separately
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add any other meta tags or links here */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
